### ISSUE TITLE
timeout not working as expected

### ISSUE THREAD

**Issue by dahartigan** [namboy94/xdcc-dl#10]
I've been able to get xdcc-dl working, however there is a particular server which requires a user be connected for at least 60 seconds.  I assume that --timeout 60 would achieve this, but it still shows that it's not waiting for the timeout, and just sends the message anyway.

Bug or am I using --timeout wrong?

**Comment by namboy94** [comment]
`--timeout` sets a time in which the download is required to start, if it does not, the program exits.

What you are trying to do can be done using the new `--wait-time` flag.
