### ISSUE TITLE
In xdcc-search, show more info when something is found and add a timeout to xdcc-dl.

### ISSUE THREAD

**Issue by msdos** [namboy94/xdcc-dl#2]
I used `xdcc-search "string" ixirc` and received:

`2019-02-22 00:27 file.rar (/msg BOT xdcc send #NUMBER)`

So I tried to used `xdcc-dl` and only got a hanging terminal. Set `--verbose` and got stuck at:

```
[2019-23-02:03-46-37] Download Limit set to: "unlimited"
[2019-23-02:03-46-37] Connecting to irc.rizon.net:6667
[2019-23-02:03-46-38] Connected to server
[2019-23-02:03-46-38] CTCP Message: ['VERSION']
[2019-23-02:03-46-38] WHOIS End
```

When searching directly on the browser, https://ixirc.com/?q=string:

```
Name | Network | Channel | User | Number | Gets | Size | Posted | Last Activity
-- | -- | -- | -- | -- | -- | -- | -- | --
2019-02-22 00:27 file.rar | Undernet | #Channel | BOT | 112 | 8 | 136 MB | 1 day ago | 15 min ago
```

So, in this specific case, I changed the `xdcc-dl` adding `--server irc.undernet.org` as a parameter and it downloaded flawlessly. IMHO all the info as in https://ixirc.com, if possible, should be added to the results in `xdcc-dl`, the download was only possible because I knew the server that was only shown on the browser.

Another suggestion: if possible, add a timeout as well to the command.

Thanks for making this project. I was looking for something exactly like this (the `xdcc-search` is really the icying on the cake I wasn't even expecting).

**Comment by namboy94** [comment]
Thanks for reporting this issue and sorry that it took so long to get to it.

In version 3.2.0 (Which should be live on pypi soon) I've implemented the following:

* ```xdcc-search``` now prints the appropriate ```xdcc-dl``` commands.
* A timeout is configurable using the ```--timeout``` option, which is by default set to 120 seconds.

If you'd like I'd also recommend a look at ```xdcc-browse```, which is basically ```xdcc-search``` with the capability to immediately download any packs that were found.

I'm glad you enjoy ```xdcc-dl```!
