### ISSUE TITLE
Is this compatible to python 2?

### ISSUE THREAD

**Issue by msdos** [namboy94/xdcc-dl#3]
I installed with `pip` using python 2, and got this error when running `xdcc-dl`:

```
xdcc-dl", line 74
    Logger().print("Thanks for using xdcc-dl!")
                 ^
SyntaxError: invalid syntax
```

When using python 3 it works. If this is a limitation, I think you should add this information to the README.

**Comment by namboy94** [comment]
Yeah, I've dropped python 2 support. I will make a note in the Readme.
