### ISSUE TITLE
Failure to join channels seems to hang xdcc-dl

### ISSUE THREAD

**Issue by morgoth1145** [namboy94/xdcc-dl#4]
I'm trying to use this to download some stuff from http://koe.anime-sharing.com/Packlist/.  However, the whois fails to find any channels (I don't know why, /whois AS|Sena in MIRC finds channels just fine) so the xdcc requests don't go out.
I did a (tiny) bit of investigation and found that on_join saw that event.source was not the username so it didn't start the download.  I hacked around this by changing on_endofwhois and adding "_.source = self.user.get_name()" before "self.on_join(conn, _)", but this doesn't seem like a good solution overall.
Also, I sometimes see xdcc-dl just hang and do nothing.  I have no clue why (or what the trigger is) though.

Here are the pip modules (and versions) that I have installed:
beautifulsoup4     4.6.3
bs4                0.0.1
certifi            2018.11.29
cfscrape           1.9.5
chardet            3.0.4
colorama           0.4.1
idna               2.8
inflect            2.1.0
irc                17.0
jaraco.classes     1.5
jaraco.collections 1.6.0
jaraco.functools   1.20
jaraco.itertools   3.0.0
jaraco.logging     1.5.2
jaraco.stream      1.2
jaraco.text        1.10.1
more-itertools     4.3.0
pip                19.0.3
pytz               2018.7
requests           2.21.0
setuptools         40.6.3
six                1.12.0
tempora            1.14
typing             3.6.6
urllib3            1.24.1
wheel              0.32.3
xdcc-dl            3.1.0

**Comment by namboy94** [comment]
I've fixed the issue in version 3.2.0, which should be live soon.
