### ISSUE TITLE
Download speed slow

### ISSUE THREAD

**Issue by m1dy** [namboy94/xdcc-dl#7]
The transfer rate of downloads never exceed 50mbit for me no matter which bot I tried. 
Tested on two different ubuntu machines in 2 different locations and same results. 

Is there some hidden download rate limit?

With this similar project https://github.com/c01eman/xdccget I easily get 800mbit+ download speed on the same machines. 

But I would rather use yours.

**Comment by namboy94** [comment]
I sadly only have a 40mbit connection, so I'll have a hard time verifying what the problem is. There shouldn't be a rate limit (you can only throttle it manually with the ```--throttle``` option, but that is set to unlimited by default)

**Comment by namboy94** [comment]
I think I've found the issue. The printing of the progress while downloading takes too much time and limits the download speed by doing so.

I'll look into fixing that.

**Comment by namboy94** [comment]
I believe I have fixed the issue by printing the progress from another thread.

The changes are now in the master branch and should be available on pypi soon.
