### ISSUE TITLE
Missing option to set channel manually

### ISSUE THREAD

**Issue by samoht0** [namboy94/xdcc-dl#8]
Thanks for your work and die recent updates! @namboy94
If a channel isn't found by WHOIS call, the request is set anyway.
"Didn't find a channel using WHOIS, trying to send message anyways"
This typically fails.
Would be nice to have an option to set channel by command line manually in those cases (option could be ignored, if WHOIS succeeds).

**Comment by namboy94** [comment]
I've added a ```--fallback-channel``` option that does exactly that.

The changes are now in the master branch and should be available on pypi soon.

**Comment by samoht0** [comment]
Gr8! Will test it, when available.
