### ISSUE TITLE
Option --silent defined twice

### ISSUE THREAD

**Issue by zmwangx** [namboy94/xdcc-dl#9]
This is most likely just unfortunate timing, but I just needed to download some files over XDCC and found your tool, and upon installing v3.3.0 (with puffotter dep v0.5.0), I was greeted with

```console
$ xdcc-dl -h
...
argparse.ArgumentError: argument --silent: conflicting option string: --silent
```

Apparently you added `--silent` to `puffotter.init.argparse_add_verbosity` in puffotter v0.5.0 but the option is still defined manually here. After removing `--silent` here the program worked flawlessly.

You're likely aware of this but I figured I'd throw a bug report your way just in case.

**Comment by namboy94** [comment]
Thanks for posting this issue, yeah that was just unfortunate timing and has since been fixed. It should work with xdcc-dl v4.0.0
